// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq6dIwYISQuvnV5PU3v4rdBsqV1MK9h9Q',
    appId: '1:933440881042:android:573ed4c4f813eab2c2414b',
    messagingSenderId: '933440881042',
    projectId: 'tracklist-3f090',
    storageBucket: 'tracklist-3f090.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVYDDc2bRHyseuujRQt_Onv14qkTsqYp8',
    appId: '1:933440881042:ios:3d6137e167d433e7c2414b',
    messagingSenderId: '933440881042',
    projectId: 'tracklist-3f090',
    storageBucket: 'tracklist-3f090.firebasestorage.app',
    iosClientId: '933440881042-3i6t9rs527it2lesgi0ml4voqel0s4li.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyDemo',
  );
}
